### ISSUE TITLE
Docs still mentions "Inputs" but this field doesn't exist anymore

### ISSUE THREAD

**Issue by gdevillele** [voxowl/particubes#145]
- [x] cleanup docs
- [x] make sure the docs auto-deploy works well

https://docs.particubes.com/reference/client#property-inputs

<img width="765" alt="Screenshot 2022-04-07 at 10 16 43" src="https://user-images.githubusercontent.com/939999/162153232-6aaa5c7d-a111-4d7a-86cc-b5b162ce8692.png">

**Comment by aduermael** [comment]
Fixed!
