### ISSUE TITLE
[Script review] Event listener

### ISSUE THREAD

**Issue by GMartigny** [voxowl/particubes#21]
Hi,

https://github.com/voxowl/particubes/blob/86713e07fa795fb58991eeb06d42eee41b2a1dd7/game-scripts/default.lua#L132-L145

From my experience as a Javascript developer, I would say it could be cleaner to add listener to an event instead of a big `switch` statement.
I don't know lua, but I would prefer something like:
```lua
Map.on(EventType.PlayerJoined, welcomeMessage)
Map.on(EventType.PlayerRemoved, byebye)

Player.on(EventType.Die, dropAboveCenter)
```

**Comment by aduermael** [comment]
Hi @GMartigny !
Sorry for the later answer...
Thank you, I agree it's easier to read, and totally doable in Lua. 

For now only `Players` and the `Server` can receive send and receive events. 

We plan to add a function that will simplify scheduling soon :

```lua
Server.Timer["10s"] = function()
	print("It's been 10 seconds!")
end
```

Maybe we should use the same semantic for events, something like:

```lua
Player.On[EventType.Die] = dropAboveCenter
```

It would also work like you said:

```lua
Player.On(EventType.Die, dropAboveCenter)
```

With anonymous function, it would look like this:

```lua
Player.On(EventType.Die, function
    -- callback definition
end)
```

We could also do it the same way. Using `[<whatever>]` notation in Lua is practical in my opinion in many cases. Things like `DB["sql:<my request>"] are lovely. But it certainly a good thing to adopt practices that are also common to Javascript developers when possible. 

cc  @gdevillele

**Comment by GMartigny** [comment]
> ```lua
> Server.Timer["10s"] = function()
> 	print("It's been 10 seconds!")
> end
> ```

Would that work if one set multiple timers ?

```lua
Server.Timer["10s"] = function()
	print("Timer 1")
end
Server.Timer["10s"] = function()
	print("Timer 2")
end
```

Thing I love in syntaxe is when it approximate native English. Some random examples:

```lua
Server.After("10s", doSomething)
Server.Every("1h", doSomething)
Player.When(EventType.Die, doSomething)
```

I only talk about JS because it's my expertise domain, but you should definitely aim for the most readable above the most widespread.

**Comment by aduermael** [comment]
No, it wouldn't work for multiple timers, but you could do something like: 

```lua
Server.Timer["10s"] = function()
	myFunction1()
	myFunction2()
end
```

It means only one timer per time period, but it's also easy to cancel it without keeping a reference:

```lua
Server.Timer["10s"] = nil
```

But I also do like the after/every/when syntax... And it can be canceled this way:

```lua
Server.timer = Server.Every("1h", doSomething)
Server.timer:Cancel()
```

**Comment by aduermael** [comment]
We know have specific functions instead of events (`OnPlayerJoin`, `OnPlayerLeave`, `OnStart`, etc.)

As for the timer, we can know schedule function calls this way:

```lua
Timer(3.5, function()
    -- this is called after 3.5 seconds
end)

Timer(3.5, true, function()
    -- this is called EVERY 3.5 seconds
end)

local t = Timer(3.5, function()
    -- this is called after 3.5 seconds
end)
t:Cancel() -- cancels the time
```
