### ISSUE TITLE
Will the engine ever be open source?

### ISSUE THREAD

**Issue by drewstone** [voxowl/particubes#50]
Hi, I’m interested in whether this game can be extended to support crypto assets / NFTs and interface with blockchain protocols. I presume the engine would need to be opened up or at least some API accumulating state would need to be exposed so game items can be uniquely identified and linked on chain. Is this in the horizon?

**Comment by aduermael** [comment]
Hi!

Sorry, crypto assets / NFTs is not on our roadmap.
We're going to provide ways for games to communicate with external servers.
It's a feature for experienced users, but it could theoretically be used to define a parallel economy in your games. 
But we sure don't want crypto to be at the core of our platform. 

We're going to open source engine components along the way, keeping the whole assembly close source for a while though.

(feel free to re-open if you have other questions)
