### ISSUE TITLE
AddBlock on MutableShape does not work correctly

### ISSUE THREAD

**Issue by caillef** [voxowl/particubes#68]
```lua
cardvmodel = MutableShape(Items.caillef.empty)
cardvmodel:AddBlock(Block(1, 1, 1, 1))
cardvmodel:AddBlock(Block(2, 2, 1, 1))
cardvmodel:AddBlock(Block(3, 3, 1, 1))
cardvmodel:AddBlock(Block(4, 4, 1, 1))
cardvmodel:AddBlock(Block(5, 5, 1, 1))
```

The blocks should be aligned but when X >= 4, they are not placed at the right spot
![image](https://user-images.githubusercontent.com/20971041/117541977-d8eb4b00-b016-11eb-864e-5966daa0b636.png)

Edit: this MutableShape is the child of a Shape that is the child of Map

**Comment by gdevillele** [comment]
@aduermael this may be related to the octree resize 😬 I think I experienced this recently

**Comment by aduermael** [comment]
This is fixed now!
